### ISSUE TITLE
Doesn't compile with latest Nodejs 21.7.3

### ISSUE THREAD

**Issue by gsbelarus** [asfernandes/node-firebird-drivers#147]
```
C:\Golden\nx\ber-info>node --version
v21.7.3

C:\Golden\nx\ber-info>npm install
npm WARN deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs
npm ERR! code 1
npm ERR! path C:\Golden\nx\ber-info\node_modules\node-firebird-native-api
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node-gyp rebuild
npm ERR! Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
npm ERR!
npm ERR!   fb-native.cpp
npm ERR! C:\Golden\nx\ber-info\node_modules\node-addon-api\napi-inl.h(48,14): error C2664: 'napi_status napi_create_external(napi_env,void *,node_api_nogc_finalize,void *,napi_value *)': cannot convert argument 3 from 'napi_finalize' to 'node_api_nogc_finalize' [C:\Golden\nx\ber-info\node_modules\node-firebird-native-api\build\addon.vcxproj]
npm ERR! C:\Golden\nx\ber-info\node_modules\node-addon-api\napi-inl.h(48,46): message : This conversion requires a reinterpret_cast, a C-style cast or parenthesized function-style cast [C:\Golden\nx\ber-info\node_modules\node-firebird-native-api\build\addon.vcxproj]
npm ERR! C:\Users\User\AppData\Local\node-gyp\Cache\21.7.3\include\node\js_native_api.h(334,1): message : see declaration of 'napi_create_external' [C:\Golden\nx\ber-info\node_modules\node-firebird-native-api\build\addon.vcxproj]
npm ERR! C:\Golden\nx\ber-info\node_modules\node-addon-api\napi-inl.h(48,14): message : while trying to match the argument list '(napi_env, FreeType *, napi_finalize, void *, napi_value *)' [C:\Golden\nx\ber-info\node_modules\node-firebird-native-api\build\addon.vcxproj]
npm ERR!           with
npm ERR!           [
npm ERR!               FreeType=Napi::AccessorCallbackData<Pointer,Napi::ObjectWrap<Pointer>::StaticGetterCallback,Napi::ObjectWrap<Pointer>::StaticSetterCallback>
npm ERR!           ]

...

npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.4.1
npm ERR! gyp info using node@21.7.3 | win32 | x64
npm ERR! gyp info find Python using Python version 3.10.11 found at "C:\Users\User\AppData\Local\Programs\Python\Python310\python.exe"
npm ERR! gyp http GET https://nodejs.org/download/release/v21.7.3/node-v21.7.3-headers.tar.gz
npm ERR! gyp http 200 https://nodejs.org/download/release/v21.7.3/node-v21.7.3-headers.tar.gz
npm ERR! gyp http GET https://nodejs.org/download/release/v21.7.3/SHASUMS256.txt
npm ERR! gyp http GET https://nodejs.org/download/release/v21.7.3/win-x64/node.lib
npm ERR! gyp http 200 https://nodejs.org/download/release/v21.7.3/SHASUMS256.txt
npm ERR! gyp http 200 https://nodejs.org/download/release/v21.7.3/win-x64/node.lib
npm ERR! gyp info find VS using VS2022 (17.6.33829.357) found at:
npm ERR! gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools"
...
```

**Comment by Tomas2D** [comment]
The same issue with Node v18.20.2
